version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edu-force-assessment-api
    ports:
      - '3005:3005'
    depends_on:
      postgres-assessment:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3005
      - NODE_OPTIONS=--max_old_space_size=512
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - edu-force-assessment-network
    command: >
      sh -c "until nc -z postgres-assessment 5432; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 2;
      done;
      echo 'PostgreSQL is ready!';
      npx prisma migrate deploy && node dist/src/main.js"

  postgres-assessment:
    image: postgres:17
    pull_policy: always
    container_name: postgres-assessment
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SHARED_BUFFERS=256MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=512MB
      - POSTGRES_WORK_MEM=16MB
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - postgres-data-assessment:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - edu-force-assessment-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  edu-force-assessment-network:
    driver: bridge

volumes:
  postgres-data-assessment:
